/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

volatile uint32_t *RCC_APB1ENR = (uint32_t *)0x40023840;	//Address offset: 0x40
volatile uint32_t *RCC_AHB1ENR = (uint32_t *)0x40023830;	//Address offset: 0x30
volatile uint32_t *GPIOA_MODER = (uint32_t *)0x40020000;
volatile uint32_t *GPIOA_AFRL = (uint32_t *)0x40020020;

volatile uint32_t *USART2_BRR = (uint32_t *)0x40004408;		//Address offset: 0x08
volatile uint32_t *USART2_CR1 = (uint32_t *)0x4000440C; 	//Address offset: 0x0C
volatile uint32_t *USART2_SR = (uint32_t *)0x40004400;
volatile uint32_t *USART2_DR = (uint32_t *)0x40004404;

int main(void) {

	*RCC_AHB1ENR |= (1 << 0);
	*RCC_APB1ENR |= (1 << 17);

	*GPIOA_MODER &= ~((1 << 4) | (1 << 5));
	*GPIOA_MODER |= (1 << 5);

	*GPIOA_MODER &= ~((1 << 6) | (1 << 7));
	*GPIOA_MODER |= (1 << 7);

	*GPIOA_AFRL &= ~((1 << 8) | (1 << 9) | (1 << 10) | (1 << 11));
	*GPIOA_AFRL |= ((1 << 8) | (1 << 9) | (1 << 10));

	*GPIOA_AFRL &= ~((1 << 12) | (1 << 13) | (1 << 14) | (1 << 15));
	*GPIOA_AFRL |= ((1 << 12) | (1 << 13) | (1 << 14));


	*USART2_BRR = 0x8B;

	*USART2_CR1 |= (1 << 13);
	*USART2_CR1 |= (1 << 2);
	*USART2_CR1 |= (1 << 3);

	while(1) {

		while((*USART2_SR & (1 << 7)) == 0) {

			//wait
		}

		*USART2_DR = 'S';

		break;
	}



}
